CC = g++

SHELL=C:/Windows/System32/cmd.exe

EXECUTABLE = proga.exe

CFLAGS = -c -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -Wextra -Wall -g -pipe -fexceptions -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body -Wformat-security -Wformat=2 -Wignored-qualifiers -Wlogical-op -Wno-missing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_DEBUG -D_EJUDGE_CLIENT_SIDE

start: main.o stack.o
	$(CC) main.o stack.o -o $(EXECUTABLE)

main.o:
	$(CC) main.cpp $(CFLAGS)

stack.o:
	$(CC) stack.cpp $(CFLAGS)

clean:
	erase D:\Study\C\Stack\*.o

run: 
	D:/Study/C/Stack/$(EXECUTABLE)